<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net8.0</TargetFramework><RootNamespace>Maple.Map</RootNamespace><AssemblyName>Maple.Map</AssemblyName><Nullable>disable</Nullable></PropertyGroup>
  <ItemGroup><ProjectReference Include="../Maple.Contracts/Maple.Contracts.csproj" /></ItemGroup>
</Project>
