<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Maple.Capture</RootNamespace>
    <AssemblyName>Maple.Capture</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Maple.Contracts/Maple.Contracts.csproj" />
  </ItemGroup>
</Project>
