#pragma once

#include <devioctl.h>
#include <guiddef.h>

DEFINE_GUID(GUID_DEVINTERFACE_MAPLE_VHF_KEYBOARD,
    0x6e6e6f4a, 0x21a5, 0x4dd2, 0x86, 0xe5, 0x7d, 0xb4, 0xc7, 0xe8, 0xa1, 0x01);

#define IOCTL_MAPLE_HID_SUBMIT_REPORT CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_MAPLE_HID_HEARTBEAT     CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_MAPLE_HID_GET_STATUS    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)
